# WARNING: This is NOT a comprehensive list. Because of the nature of the config
# system, it is possible to create a new 'type' simply by choosing a different string
# when coding it.
#
# Meaningful Properties (they do not show up in autocomplete):
# * `discourage_in_creation_ui`
#   When you add an `instead`, prefer using the named route, such as :feature_flags_config
# * `default_config_name`
#   When creating a config, this will be the default.
# Everything else just gets dumped out for the user to see.
#
# `known_properties` is mostly to make sure it's easy for the autocomplete to match something.
---
auth0:
  description: Auth0 is a special login solution wanted by some customers.
  cs_wiki: https://sites.google.com/a/socrata.com/client-services/security/auth0-login-flows
  known_properties:
  - auth0_connections
  - auth0_callback_uri
  - auth0_always_redirect_connection
  - auth0_message
  - require_sso_for_rights
catalog:
  holy_shit: There is a lot of magic in this config.
  cs_wiki: https://sites.google.com/a/socrata.com/client-services/5-site-configurations/catalog-options
  new_catalog_info: https://sites.google.com/a/socrata.com/client-services/4-adding-additional-site-features/enabling-new-catalog
  known_properties:
  - sortBy
  - limit
  - limitTo
  - facet_cutoffs
  - view_types_facet
  - federation_filter
  - data-json-schema-version
  - official_boost
  property_type_checking:
    custom_facets: Array
    official_boost: Number
catalog_federations:
  description: Used by core server. Not sure for what.
  discourage_in_creation_ui:
    reason: :poorly_understood
catalog_landing_page:
  description: The Discovery team is using this to manage metadata for Catalog Landing Pages.
  discourage_in_creation_ui:
    reason: :not_intended_for_direct_manipulation
custom_content:
  description: Appears to be for oldest DataSlate? Not sure what this actually does.
  deprecation: "Let's just... not use this, yeah?"
  discourage_in_creation_ui:
    reason: :deprecation
data_lens_config:
  description: Miscellaneous configuration for Data Lens.  If choropleth_custom_boundary is specified as a WKT string, choropleths in Data Lens will only render regions completely contained within this polygon.  See http://arthur-e.github.io/Wicket/sandbox-gmaps3.html to generate a WKT string.
  known_properties:
  - choropleth_custom_boundary
dataslate_config:
  description: 'Configuration for Dataslate pages, intended for direct manipulation by CS developers to configure how the platform should render Dataslate pages. Note: `prevent_platform_styling` expects an array of RegExp strings matching the page paths you want to prevent styling on.'
  known_properties:
  - prevent_platform_styling
  property_type_checking:
    prevent_platform_styling: Array
    staging_lockdown_exceptions: Array
email_interests:
  description: "Found this deep in core. I don't understand it yet."
  discourage_in_creation_ui:
    reason: :poorly_understood
feature_set:
  warning: "This is a visible config so that you can delete features. DO NOT set their values! If you're lucky, it will be fine; if you're unlucky, it will break things."
  discourage_in_creation_ui:
    reason: :not_intended_for_direct_manipulation
feature_flags:
  discourage_in_creation_ui:
    reason: :not_intended_for_direct_manipulation
    instead: :feature_flags_config
geo_setup:
  description: Something to do with setting up region coding when syncing to NBE.
  discourage_in_creation_ui:
    reason: :deprecation
    instead: :georegions_administration
  known_properties:
  - curated_regions
geocoding:
  description: Configuration for geocoding default values and provider.
  documentation: https://docs.google.com/document/d/1la6JkdyyaKUNit3AaBX_B9_pWmgG2v7B1DekZQ0sKaY/view
  how_to_use_defaults: '"defaults" should be a json object with the optional fields: "country", "region", "subregion", "postal_code", "locality", "address".'
  how_to_use_provider: '"provider" should be a supported provider: "mapquest", "esri"'
  known_properties:
  - defaults
  - provider
gov_stat:
  description: Configure displays. Dashboard can be list or grid_flow.
  default_config_name: Open Performance Settings
  how_to_suppress_govstat: https://sites.google.com/a/socrata.com/client-services/2-editing-an-open-data-site/supressing-open-performance-govstat-config
  known_properties:
  - suppress_govstat
  - dashboard_layout
icon:
  description: Icon to use when federating datasets from this domain. Use the wiki-suggested method instead of this.
  default_config_name: Federation Icon Id
  cs_wiki: https://sites.google.com/a/socrata.com/client-services/5-site-configurations/adding-the-small-icon-for-federation
  known_properties:
  - id
locales:
  description: Handle which locales are available for this domain, which is the default, and also different defaults for language-specific aliases.
  default_config_name: Locale Settings
  cs_wiki: https://sites.google.com/a/socrata.com/client-services/localization/localizing-content
  also_see_subpages_of: https://sites.google.com/a/socrata.com/client-services/localization
  known_properties:
  - '*'
  - available_locales
  property_type_checking:
    available_locales: Array
metadata:
  description: This holds the values from /admin/metadata.
  discourage_in_creation_ui:
    reason: :not_intended_for_direct_manipulation
    instead: :metadata_administration
nbe_timezone:
  description: Configures which time zone your datasets are presumed to be in when ingressing.
  known_properties:
  - name
nbe_query_timeouts:
  description: Configuration to specify timeout values in seconds for various NBE queries.
  known_properties:
  - in_dataset_search
quotas:
  cs_wiki_admins: https://sites.google.com/a/socrata.com/client-services/5-site-configurations/allowing-extra-administrators
  cs_wiki_snapshots: https://sites.google.com/a/socrata.com/client-services/5-site-configurations/snapshot-counts
sidebar:
  description: Position old UX sidebar on left or right; open a pane by default when loading a dataset.
  cs_wiki: https://sites.google.com/a/socrata.com/client-services/5-site-configurations/default-pane-on-dataset-non-datalens-pages
  known_properties:
  - position
  - default_pane
site_chrome:
  description: Site header/footer configuration. Edit it at /admin/site_appearance
  discourage_in_creation_ui:
    reason: :not_intended_for_direct_manipulation
    instead: /admin/site_appearance
site_theme:
  cs_wiki: https://sites.google.com/a/socrata.com/client-services/2-editing-an-open-data-site/a-site-configurations
  things_site_theme_controls: favicon
soda2:
  known_properties:
  - switch_table_rows_threshold
story_theme:
  description: Storyteller custom themes. The admin ui is at /stories/admin/themes
  discourage_in_creation_ui:
    reason: :not_intended_for_direct_manipulation
    instead: /stories/admin/themes
theme_v3:
  description: Data Lens theme for customizing logo_url, sign up/in/out links.
upload_record_limit:
  description: Change the maximum number of rows for DI2 import.
  how_to_override_row_limits: https://docs.google.com/document/d/1wWtGTw00Gmon2QRyUBRHDahubCc6Fbqdz_RbK8W6U4M/edit
  known_properties:
  - large_4x4s
  - disable_all_record_limits
user_rights:
  description: Blah blah. This is dangerous, etc., etc.
  known_properties:
  - administrator
  - designer
  - editor
  - publisher
  - viewer
  cs_wiki: https://sites.google.com/a/socrata.com/client-services/5-site-configurations/users/how-to-manually-set-user-rights-on-a-domain
  kb_page: https://support.socrata.com/hc/en-us/articles/202950278-Understanding-user-roles
  short_session: You can configure roles to have a shorter user-session timeout (15 minutes) using the right called `short_session`.
  discourage_in_creation_ui:
    reason: :poorly_understood
view_categories:
  description: Holds the categories that views can be. Managed by /admin/metadata.
  discourage_in_creation_ui:
    reason: :not_intended_for_direct_manipulation
    instead: :metadata_administration
visualization_canvas:
  cs_wiki: https://sites.google.com/a/socrata.com/client-services/creating-and-configuring-platform-domains/additional-platform-configurations/visualization-canvas-customizations
  description: Customer-specific tweaks to the Visualization Canvas asset type.
  known_properties:
  - hide_data_source_link
