# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c7a57c1b9c8c5b5aa03ff965a3795b160432b02aa9de5edc5c8336592605ccdbd73dd52426ba5dc78937715f5356d370be822a0ed3b0f301ac146c6c8f38049
  session_store_secret: 740b5aac6b32f3ae849519faf72be9a03a9d36d63f4c2ca6e6badaa8b921054337e66070e27a7bd6eaa3a5ec4c2659396471f69fd01428314b3cb97638992637
  session_salt: jp3sztH+CnGV64B3A7tzTBRx2Yp*qF-U

test:
  secret_key_base: c6cf96fde18d15109df128f78cdd45c7d8dcb23db4bd34e5d18643def8851f785ea81d330edbe13c7b2e5273269319507d317ec96ee2a8c9355445e6a37be923
  session_store_secret: bbdaa01fb69608decbb1d2cfd0fcc14b1b798d242fbcf9b954659952fca4ee4d33b6cd7c076ea1b3073cbf7458b31a8067a80f2d562635a64d8cbeeec67a5364
  session_salt: +9h9j3YcK3A8aPz[2Dq-weo*UJeRvgddbT

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  session_store_secret: <%= ENV['SESSION_STORE_SECRET'] %>
  session_salt: <%= ENV['SESSION_SALT'] %>

staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  session_store_secret: <%= ENV['SESSION_STORE_SECRET'] %>
  session_salt: <%= ENV['SESSION_SALT'] %>

rc:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  session_store_secret: <%= ENV['SESSION_STORE_SECRET'] %>
  session_salt: <%= ENV['SESSION_SALT'] %>
