# Scheduled downtime notifications go here
# Example:
# start: 2010-08-08t00:00:00-08:00
# end:   2010-08-09t00:00:00-08:00
# message: We are performing scheduled maintenance during...
#
# NOTE: If you leave off an 'end' param, it will keep displaying until the config
# is removed. Useful if you want it to persist until the next deploy, during
# which the notification is removed from this file.
# Similarly, if you leave off a 'start' param, the message will be displayed
# until it is removed from this file

start: 2013-11-13t17:00-08:00
end: 2013-11-15t18:00:00-08:00
message: This Socrata-powered site may be unavailable for routine maintenance Saturday, November 15th from 5:00pm-6:00pm PST.

