# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    s3_bucket_name: sa-storyteller-dev-us-west-2-staging
    secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  secret_key_base: 33fb81dc50972464853e21873ef782ebfe4a3e8472566f734eb5e135baa4a94bfdb89b47ff5e7df4c305520e93607b42663a72070909bcf78ecf2dedb4360ef6

test:
  aws:
    access_key_id: ''
    s3_bucket_name: 'test-bucket'
    secret_access_key: ''
  secret_key_base: d921263a5b712a959f6a6d394a394629c1acf370d4dd18f4a40c9a68d2a4eef194f58b2ee6c7a46c3bcdfe0287288fda2e0e092ebbd94645a0e49a01cc62e69c

# Purposefully empty. We use this rails env for aws migrations, but we don't
# need any configurations in here. The aws.rb initializer requires that these
# keys exist.
aws_migrations:
  aws:
    access_key_id:
    s3_bucket_name:
    secret_access_key:
  secret_key_base:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    s3_bucket_name: <%= ENV['AWS_S3_BUCKET_NAME'] %>
    secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
