includes:
- sass-common
- icons
base:
- base
- layout
- common
- forms
- old-controls
- controls
- tables
base-sdp:
- base
- common
- forms
- old-controls
- controls
- tables
- table-core
- dataset-grid
- control-feed
strip-chrome:
- strip-chrome
screen-login:
- screen-login
screen-map:
- screen-map
screen-calendar:
- screen-calendar
administration-screen:
- screen-admin
administration-datasets:
- screen-administration-datasets
administration-select-dataset:
- screen-administration-select-dataset
administration-federation:
- screen-administration-federation
administration-home:
- screen-administration-home
administration-index-screen:
- screen-admin-index
administration-analytics-screen:
- screen-metrics
administration-metadata:
- screen-administration-metadata
administration-moderation:
- screen-administration-moderation
administration-sdp-templates:
- screen-admin-sdp-templates
administration-sdp-template:
- grid-sidebar
- screen-admin-customizer
administration-stories-appearance:
- grid-sidebar
- screen-homepage-show-reset
- screen-homepage-show
- screen-admin-customizer
administration-users:
- screen-admin-users
administration-view-moderation:
- screen-administration-views
browse-control:
- screen-browse
dataset-new:
- screen-dataset-new
dataset-show:
- grid-sidebar
- grid-sidebar-custom
- table-core
- dataset-grid
- control-feed
- splash
- about-dataset
- screen-dataset
dataset-alt:
- screen-dataset-alt
dataset-analytics:
- screen-metrics
dataset-edit-metadata:
- screen-dataset-edit-metadata
dataset-edit-rr:
- grid-sidebar
- table-core
- dataset-grid
- render-type-images
- rich-render-types
- screen-dataset-edit-rr
dataset-thumbnail:
- screen-dataset-thumbnail
dataset-upload:
- screen-dataset-upload
dataset-bare:
- screen-dataset-bare
error-pages:
- screen-error-pages
internal:
- screen-internal
internal-metrics:
- screen-metrics
homepage-show:
- screen-homepage-show
profile-show:
- screen-profile
- screen-profile-shared
- control-feed
profile-edit:
- screen-profile-edit
- screen-profile-shared
screen-nominations:
- screen-nominations
screen-videos:
- screen-videos
screen-videos-popup:
- strip-chrome
- screen-videos-popup
html-styles:
- table-core
- dataset-grid
